import { defineConfig } from "@playwright/test";

export default defineConfig({
  fullyParallel: false,
  projects: [{ name: "contracts" }],
  reporter: [["list"]],
  testDir: "./tests/e2e",
  testMatch: [
    "catalog-resource-dependencies.spec.ts",
    "channel-adapter-conformance.spec.ts",
    "channel-adapter.spec.ts",
    "channel-certification.spec.ts",
    "channel-plugin-boundaries.spec.ts",
    "conversation-control-intents.spec.ts",
    "conversation-diagnostics.spec.ts",
    "conversation-turn-contracts.spec.ts",
    "conversation-turn-engine.spec.ts",
    "conversational-task-runtime.spec.ts",
    "conversational-task-schema.spec.ts",
    "flow-content-components.spec.ts",
    "flow-content-contracts.spec.ts",
    "flow-content-lifecycle.spec.ts",
    "flow-content-runtime.spec.ts",
    "flow-message-editor.spec.ts",
    "hybrid-flow.spec.ts",
    "media-storage-contract.spec.ts",
    "model-tool-conformance.spec.ts",
    "phase17-analytics.spec.ts",
    "runtime-action-experiments.spec.ts",
    "runtime-stage-timing.spec.ts",
    "telnyx-voice.spec.ts",
    "whatsapp-template-contracts.spec.ts",
  ],
  timeout: 30_000,
});
