import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import { Navigation } from "@/components/navigation";
import { NavigationProgress } from "@/components/navigation-progress";
import { NavigationShell } from "@/components/navigation-shell";
import { FormScrollRestoration } from "@/components/ui/form-scroll-restoration";
import { Toaster } from "@/components/ui/sonner";
import { UrlFlashToasts } from "@/components/ui/url-flash-toasts";
import "@xyflow/react/dist/style.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <NavigationProgress />
          <FormScrollRestoration />
          <UrlFlashToasts />
        </Suspense>
        <NavigationShell>
          <Navigation />
        </NavigationShell>
        {children}
        <Toaster closeButton position="bottom-right" richColors />
      </body>
    </html>
  );
}
